cms/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from cms.views import (
    LoginView, 
    LogoutView, 
    AdminView, 
    ProjectView, 
    ProjectAddView,
    ProjectDeleteView
)

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^main/$', AdminView.as_view(), name='admin-main'),
    url(r'^projects/$', ProjectView.as_view(), name='projects'),
    url(r'^projects/add/$', ProjectAddView.as_view(), name='projects-add'),
    url(r'^projects/(?P<pk>[0-9]+)/delete/$', ProjectDeleteView.as_view(), name='projects-delete'),
    # url(r'^projects/(?P<pk>[0-9]+)/update/$', ProjectUpdateView.as_view(), name='projects.update'),
]

django_site/urls.py
from django.conf.urls import include, url
# from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^main/', include('portfolio.urls', namespace='portfolio')),
    url(r'^admin/', include('cms.urls', namespace='cms')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.conf.urls import url
from portfolio.views import MainPage
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^$', MainPage.as_view(), name='main'),

]

cms/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    class Meta:
        db_table = 'Project'

    title = models.CharField(max_length=25)
    content = models.TextField()
    photo = models.ImageField()
    url = models.URLField()
    user = models.ForeignKey(User)

cms/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, models as dj
from cms import models as pf


class UploadFileForm(forms.ModelForm):
    class Meta:
        model = pf.Project
        fields = ['title', 'content', 'photo', 'url']
        exclude = ['user']
        labels = {
            'title': _('Select title for the project:'),
            'url': _('Set up URL for the project:'),
            'content': _('Description of the project:'),
            'photo': _('Add photo for the project:'),
        }
        widgets = dict(
            title=forms.TextInput(attrs={'class': 'form-control'}),
            url=forms.TextInput(attrs={'class': 'form-control'}),
            content=forms.Textarea(attrs={'class': 'form-control'}),
        )
        error_messages = dict(
            title=dict(
                required=_('Title is required(max: 25)'),
            ),
            url=dict(required=_('Url is required')),
            content=dict(
                required=_('Content is required(max: no limit)'),
            ),
            photo=dict(required=_('You don\'t select a photo')),
        )  


class LoginForm(AuthenticationForm):
    
    username = forms.CharField(
        label=_("Username"), 
        max_length=254,
        error_messages={
            'required': _('Username is required')
        },
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'id': 'username'
        }),
    )
    password = forms.CharField(
        label=_("Password"), 
        error_messages={
            'required': _('Password is required')
        },
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'id': 'password'
        }),
    )

cms/views.py
import os
import json
from django.shortcuts import get_object_or_404, redirect
from django.http import JsonResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse_lazy
from django.template import RequestContext
from django_site.settings import BASE_DIR
from django.views.generic import View, TemplateView, ListView, RedirectView
from django.views.generic.edit import FormView, CreateView, DeleteView
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.models import User

from cms.models import Project
from cms.forms import LoginForm, UploadFileForm
from bl.view_helpers import generate_new_filename
from bl.mixins import AjaxableResponseMixin, LoginRequiredMixin


class LoginView(AjaxableResponseMixin, FormView):

    template_name = 'cms/auth.html'
    form_class = LoginForm
    success_url = reverse_lazy('cms:admin-main')

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        context['redirect_url'] = self.success_url
        return context

    def form_valid(self, form):
        # import pdb; pdb.set_trace()
        login(self.request, form.get_user())
        return super(FormView, self).form_valid(form)


class LogoutView(LoginRequiredMixin, RedirectView):

    url = '/admin/login/'

    def post(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class AdminView(LoginRequiredMixin, TemplateView):

    template_name = 'cms/pages/main.html'


class ProjectView(LoginRequiredMixin, ListView):

    template_name = 'cms/pages/projects.html'
    model = Project
    context_object_name = 'projects'


class ProjectAddView(LoginRequiredMixin, AjaxableResponseMixin, CreateView):

    template_name = 'cms/pages/projects.add.html'
    form_class = UploadFileForm
    success_url = reverse_lazy('cms:projects')

    def form_valid(self, form):
        # import pdb; pdb.set_trace()
        project = form.save(commit=False)
        project.user = User.objects.get(id=self.request.user.id)
        project.photo.name = generate_new_filename(project.photo.name)
        project.save()
        return super(ProjectAddView, self).form_valid(form)


class ProjectDeleteView(LoginRequiredMixin, DeleteView):

    model = Project
    success_url = reverse_lazy('cms:projects-main')

    def delete_photo_from_path(self, *args, **kwargs):
        try:
            os.remove(self.object.photo.path)
        except AttributeError as e:
            return JsonResponse(data={"error": "Photo not found"}, status=404)        

    def delete(self, request, *args, **kwargs):
        # import pdb; pdb.set_trace()
        self.object = self.get_object()
        self.delete_photo_from_path()
        self.object.delete()
        return JsonResponse(
            data={"success": "Project %(pk)d successfully deleted" % {"pk": int(self.kwargs['pk'])}}, 
            status=200
        )


# @login_required(login_url='/')
# def delete_project(request):
#     if request.is_ajax():
#         if request.method == 'DELETE':
#             data = json.loads(request.body)
#             prj = Project.objects.get(id=data['prj_id'])
#             path = str(prj.photo_name.path)
#             prj.delete()
#             os.remove(path)
#             return HttpResponse()

portfolio/views.py
from django.views.generic import ListView
from django.shortcuts import render
from cms.models import Project


class MainPage(ListView):
    template_name = 'portfolio/index.html'
    model = Project
    context_object_name = 'projects'

cms/templates/cms/auth.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Bootstrap Login Form</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    {% load staticfiles %}
		<link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="{% static 'cms/css/styles.css' %}" rel="stylesheet">
	</head>
	<body>
    <!--login modal-->
    <div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="text-center">Login</h1>
            </div>
            <div class="modal-body">
                <form id="signIn" class="form col-md-12 center-block" method="post" action="{% url 'cms:login' %}">
                  <div class="form-group">
                    <input id="main" type="hidden" value="{{ redirect_url }}" />
                  </div>                  
                  <div class="form-group">
                    {% csrf_token %}
                  </div>
                  {% for field in form %}
                  <div class="form-group">
                    {{ field }}
                  </div>
                  <div id="ajax_error_{{ field.name }}">
                  </div> 
                  {% endfor %}
                  <div id="ajax_error___all__">
                  </div> 
                  <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg btn-block">Sign In</button>
                  </div>             
                </form>
            </div>
            <div class="modal-footer">
              <div class="col-md-12">
      		    </div>	
            </div>
        </div>
      </div>
    </div>
    <!-- script references -->
		<script src="{% static 'jquery.js' %}"></script>
		<script src="{% static 'bootstrap.min.js' %}"></script>
    <script src="{% static 'cms/js/custom.js' %}"></script>
	</body>
</html>

cms/templates/cms/index.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin - Bootstrap Admin Template</title>

    {% load staticfiles %}
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'cms/css/sb-admin.css' %}" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="{% static 'cms/css/plugins/morris.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'cms/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        {% include 'cms/index/navbar.html' %}

        <div id="page-wrapper">
        {% block content %}
        {% endblock %}
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="{% static 'jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'bootstrap.min.js' %}"></script>

    <!-- Custom JQuery -->
    <script src="{% static 'cms/js/custom.js' %}"></script>

    <!-- Morris Charts JavaScript -->
    <script src="{% static 'cms/js/plugins/morris/raphael.min.js' %}"></script>
    <script src="{% static 'cms/js/plugins/morris/morris.min.js' %}"></script>
    <script src="{% static 'cms/js/plugins/morris/morris-data.js' %}"></script>

</body>

</html>

cms/templates/cms/index/navbar.html
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html">Devportfolio Admin</a>
    </div>
    <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{  user.username }} <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li>
                    <form class="form col-md-12" action="{% url 'cms:logout' %}" method="post">
                        {% csrf_token %}
                        <a href="javascript:;" onclick="parentNode.submit();"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                    </form>
                </li>
            </ul>
        </li>
    </ul>
    <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
            {% url 'cms:admin-main' as main_url %}
            <li class="{% if current_path == main_url %}active{% endif %}">
                <a href="{{ main_url }}"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-fw fa-bar-chart-o"></i> Charts</a>
            </li>
            {% url 'cms:projects' as projects_url %}
            {% url 'cms:projects-add' as projects_add_url %}
            <li class="{% if current_path == projects_url or current_path == projects_add_url %}active{% endif %}">
                <a id="test" href="#" data-toggle="collapse" data-target="#projects" {% if current_path == projects_url or current_path == projects_add_url %} class aria-expanded="true" {% else %} class="collapse" aria-expanded="false" {% endif %}><i class="fa fa-fw fa-table"></i> Projects <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="projects" {% if current_path == projects_url or current_path == projects_add_url %} aria-expanded="true" class="colapse in"{% else %} class="collapse" {% endif %}>
                    <li>
                        <a href="{{ projects_url }}">Overview</a>
                    </li>
                    <li>
                        <a href="{{ projects_add_url }}">New project</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-fw fa-edit"></i> Forms</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-fw fa-desktop"></i> Bootstrap Elements</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-fw fa-wrench"></i> Bootstrap Grid</a>
            </li>
            <li>
                <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Dropdown <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="demo" class="collapse">
                    <li>
                        <a href="#">Dropdown Item</a>
                    </li>
                    <li>
                        <a href="#">Dropdown Item</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="blank-page.html"><i class="fa fa-fw fa-file"></i> Blank Page</a>
            </li>
            <li>
                <a href="index-rtl.html"><i class="fa fa-fw fa-dashboard"></i> RTL Dashboard</a>
            </li>
        </ul>
    </div>
    <!-- /.navbar-collapse -->
</nav>

cms/templates/cms/pages/blank-page.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin - Bootstrap Admin Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/sb-admin.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">SB Admin</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu message-dropdown">
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading">
                                            <strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-footer">
                            <a href="#">Read All New Messages</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">View All</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Smith <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <a href="index.html"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="charts.html"><i class="fa fa-fw fa-bar-chart-o"></i> Charts</a>
                    </li>
                    <li>
                        <a href="tables.html"><i class="fa fa-fw fa-table"></i> Tables</a>
                    </li>
                    <li>
                        <a href="forms.html"><i class="fa fa-fw fa-edit"></i> Forms</a>
                    </li>
                    <li>
                        <a href="bootstrap-elements.html"><i class="fa fa-fw fa-desktop"></i> Bootstrap Elements</a>
                    </li>
                    <li>
                        <a href="bootstrap-grid.html"><i class="fa fa-fw fa-wrench"></i> Bootstrap Grid</a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Dropdown <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo" class="collapse">
                            <li>
                                <a href="#">Dropdown Item</a>
                            </li>
                            <li>
                                <a href="#">Dropdown Item</a>
                            </li>
                        </ul>
                    </li>
                    <li class="active">
                        <a href="blank-page.html"><i class="fa fa-fw fa-file"></i> Blank Page</a>
                    </li>
                    <li>
                        <a href="index-rtl.html"><i class="fa fa-fw fa-dashboard"></i> RTL Dashboard</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Blank Page
                            <small>Subheading</small>
                        </h1>
                        <ol class="breadcrumb">
                            <li>
                                <i class="fa fa-dashboard"></i>  <a href="index.html">Dashboard</a>
                            </li>
                            <li class="active">
                                <i class="fa fa-file"></i> Blank Page
                            </li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

cms/templates/cms/pages/projects.add.html
{% extends 'cms/index.html' %}
{% load staticfiles %}

{% block content %}
<div class="container-fluid">

  <!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
          <h1 class="page-header">
              Projects <small>Create new</small>
          </h1>
      </div>
  </div>
  <!-- /.row -->

  <div class="row">
    <form class="form col-md-6" enctype="multipart/form-data" method="post" action="{% url 'cms:projects-add' %}">
      <div class="form-group">
        {% csrf_token %}
      </div>
      {% for field in form %}
      <div class="form-group">
        {{ field.label }}{{ field }}
      </div>
      <div class="form-group" style="color: red;">
        {{ field.errors }}
      </div>      
      {% endfor %}
      <input class="btn btn-default" value="Add new project" type="submit" />
    </form>
  </div>
    <!-- /.row -->
</div>
<!-- /.container-fluid -->
{% endblock %}

cms/templates/cms/pages/projects.html
{% extends 'cms/index.html' %}
{% load staticfiles %}
{% block content %}
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Projects <small>Overview</small>
            </h1>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div id="success_delete" class="col-lg-12">
        </div>
    </div>
    <!-- /.row -->
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-dashboard"></i><span> Dashboard</span>
        </div>
        <div class="panel-body">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Content</th>
                        <th>Photo</th>
                        <th>URL</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for project in projects %}
                    <tr id="prj_{{ project.id }}">
                        <td>{{ project.title }}</td>
                        <td>{{ project.content }}</td>
                        <td><img src="{{ MEDIA_URL }}{{ project.photo }}" class="img-responsive" alt="Cinque Terre" width="200" height="250"></td>
                        <td>{{ project.url }}</td>
                        <td>
                            <form class="form col-md-6" method="" action="{% url 'cms:projects-delete' pk=project.id %}">
                                <button class="btn btn-danger delete_project">Delete</button>
                                {% csrf_token %}
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
{% endblock %}

portfolio/templates/portfolio/aboutSection.html
<section class="success" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>About</h2>
                <hr class="star-light">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-lg-offset-2">
                <p>Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional LESS stylesheets for easy customization.</p>
            </div>
            <div class="col-lg-4">
                <p>Whether you're a student looking to showcase your work, a professional looking to attract clients, or a graphic artist looking to share your projects, this template is the perfect starting point!</p>
            </div>
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <a href="#" class="btn btn-lg btn-outline">
                    <i class="fa fa-download"></i> Download Theme
                </a>
            </div>
        </div>
    </div>
</section>

portfolio/templates/portfolio/header.html
{% load staticfiles %}
<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!--<img class="img-responsive" src="{% static 'portfolio/img/profile.png' %}" alt="">-->
                <div class="intro-text">
                    <span class="name">Start Bootstrap</span>
                    <hr class="star-light">
                    <span class="skills">Web Developer - Graphic Artist - User Experience Designer</span>
                </div>
            </div>
        </div>
    </div>
</header>